/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TwitterView.java
 *
 * Created on 16/08/2012, 6:30:55 PM
 */
package com.java.twitteranalyzer;

import com.java.twitteranalyzer.dialogbox.AboutBox;
import com.java.twitteranalyzer.dialogbox.HelpBox;
import com.java.twitteranalyzer.chart.BarChart;
import com.java.twitteranalyzer.chart.StackedBarChart;
import com.java.twitteranalyzer.chart.PieChart;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.SwingWorker;

/**
 *
 * @author YZY
 */
public class TwitterAnalyzerView extends javax.swing.JFrame implements KeyListener{

    BackGroundAnalyzer analyzer;
    BackGroundAnalyzer analyzer2;
    FileProcessor fileProcessor;
    
    
    /** Creates new form TwitterView */
    public TwitterAnalyzerView() {
        analyzer = new BackGroundAnalyzer();
        analyzer2 = new BackGroundAnalyzer();
        fileProcessor = new FileProcessor();
        
        
        initComponents();
        
        /* Center the frame. */
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();  
        Rectangle frame = getBounds();  
        setLocation((screen.width - frame.width)/2, (screen.height - frame.height)/2); 

        /* Add key listeners for the text fields. */
        topicTextField1.addKeyListener(this);
        topicTextField2.addKeyListener(this);
        tweetsPerPageTextField.addKeyListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fileDialog = new javax.swing.JDialog();
        fileChooser = new javax.swing.JFileChooser("save\\");
            jPanel2 = new javax.swing.JPanel();
            jPanel1 = new javax.swing.JPanel();
            topicTextField2 = new javax.swing.JTextField();
            topicTextField1 = new javax.swing.JTextField();
            jLabel4 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            userCount1 = new javax.swing.JLabel();
            userCount2 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jPanel3 = new javax.swing.JPanel();
            jProgressBar2 = new javax.swing.JProgressBar();
            jLabel1 = new javax.swing.JLabel();
            clearButton = new javax.swing.JButton();
            searchButton = new javax.swing.JButton();
            NumberFormat intFormat = NumberFormat.getNumberInstance();
            intFormat.setMaximumIntegerDigits(3);
            tweetsPerPageTextField = new JFormattedTextField(intFormat);
            jLabel2 = new javax.swing.JLabel();
            chartPanel = new javax.swing.JPanel();
            jMenuBar1 = new javax.swing.JMenuBar();
            jMenu1 = new javax.swing.JMenu();
            saveMenuItem = new javax.swing.JMenuItem();
            openMenuItem = new javax.swing.JMenuItem();
            jMenu5 = new javax.swing.JMenu();
            jRadioButtonMenuItem_ratio = new javax.swing.JRadioButtonMenuItem();
            jRadioButtonMenuItem_daily = new javax.swing.JRadioButtonMenuItem();
            jRadioButtonMenuItem_gender = new javax.swing.JRadioButtonMenuItem();
            jRadioButtonMenuItem_url = new javax.swing.JRadioButtonMenuItem();
            jMenu2 = new javax.swing.JMenu();
            jMenuItem1 = new javax.swing.JMenuItem();
            jMenuItem2 = new javax.swing.JMenuItem();

            javax.swing.GroupLayout fileDialogLayout = new javax.swing.GroupLayout(fileDialog.getContentPane());
            fileDialog.getContentPane().setLayout(fileDialogLayout);
            fileDialogLayout.setHorizontalGroup(
                fileDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 582, Short.MAX_VALUE)
            );
            fileDialogLayout.setVerticalGroup(
                fileDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 397, Short.MAX_VALUE)
            );

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Twitter Analyzer");
            setName("mainFrame"); // NOI18N
            setResizable(false);

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search topics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

            topicTextField2.setText("#TaylorSwift");

            topicTextField1.setText("#FIFA");

            jLabel4.setText("Topic2: ");

            jLabel3.setText("Topic1:");

            userCount1.setText("0");

            userCount2.setText("0");

            jLabel6.setText("users");

            jLabel7.setText("users");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(topicTextField1)
                        .addComponent(topicTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(userCount1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(userCount2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(topicTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userCount1)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(topicTextField2)
                        .addComponent(userCount2)
                        .addComponent(jLabel7))
                    .addContainerGap())
            );

            jLabel1.setForeground(new java.awt.Color(204, 102, 0));
            jLabel1.setText("Ready to analyze");

            clearButton.setText("Clear");
            clearButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    clearButtonActionPerformed(evt);
                }
            });

            searchButton.setText("Search");
            searchButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    searchButtonActionPerformed(evt);
                }
            });

            tweetsPerPageTextField.setText("15");

            jLabel2.setText("Number of tweets: 10 *");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(33, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(tweetsPerPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(searchButton))
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchButton)
                        .addComponent(clearButton)
                        .addComponent(tweetsPerPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                    .addContainerGap(14, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            chartPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            chartPanel.setLayout(new java.awt.GridLayout(1, 2));

            jMenu1.setText("File");

            saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
            saveMenuItem.setLabel("Save...");
            saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    saveMenuItemActionPerformed(evt);
                }
            });
            jMenu1.add(saveMenuItem);

            openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
            openMenuItem.setText("Open...");
            openMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    openMenuItemActionPerformed(evt);
                }
            });
            jMenu1.add(openMenuItem);

            jMenuBar1.add(jMenu1);

            jMenu5.setText("View");

            jRadioButtonMenuItem_ratio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
            buttonGroup1.add(jRadioButtonMenuItem_ratio);
            jRadioButtonMenuItem_ratio.setLabel("Follower/Friend Ratio");
            jRadioButtonMenuItem_ratio.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButtonMenuItem_ratioActionPerformed(evt);
                }
            });
            jMenu5.add(jRadioButtonMenuItem_ratio);

            jRadioButtonMenuItem_daily.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
            buttonGroup1.add(jRadioButtonMenuItem_daily);
            jRadioButtonMenuItem_daily.setSelected(true);
            jRadioButtonMenuItem_daily.setText("Daily Activity");
            jRadioButtonMenuItem_daily.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButtonMenuItem_dailyActionPerformed(evt);
                }
            });
            jMenu5.add(jRadioButtonMenuItem_daily);

            jRadioButtonMenuItem_gender.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
            buttonGroup1.add(jRadioButtonMenuItem_gender);
            jRadioButtonMenuItem_gender.setText("Gender");
            jRadioButtonMenuItem_gender.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButtonMenuItem_genderActionPerformed(evt);
                }
            });
            jMenu5.add(jRadioButtonMenuItem_gender);

            jRadioButtonMenuItem_url.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
            buttonGroup1.add(jRadioButtonMenuItem_url);
            jRadioButtonMenuItem_url.setText("Profile URL");
            jRadioButtonMenuItem_url.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButtonMenuItem_urlActionPerformed(evt);
                }
            });
            jMenu5.add(jRadioButtonMenuItem_url);

            jMenuBar1.add(jMenu5);

            jMenu2.setText("Help");

            jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
            jMenuItem1.setText("Help Contens");
            jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem1ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem1);

            jMenuItem2.setText("About");
            jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem2ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem2);

            jMenuBar1.add(jMenu2);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chartPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents


    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            TweetSearcher searcher = new TweetSearcher();
            searcher.execute();
            }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }
    
    
private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
// TODO add your handling code here:
    TweetSearcher searcher = new TweetSearcher();
    searcher.execute();
           
}//GEN-LAST:event_searchButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        topicTextField1.setText(null);
        topicTextField2.setText(null);
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jRadioButtonMenuItem_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem_genderActionPerformed
        // TODO add your handling code here:
        if (!analyzer.mHashMap.isEmpty()) {
            chartPanel.removeAll();
            chartPanel.add(new PieChart(
                        "Gender ("+topicTextField1.getText()+")",
                        analyzer.summaryGenderData(analyzer.mHashMap),
                        chartPanel.getSize()));
            chartPanel.add(new PieChart(
                        "Gender ("+topicTextField2.getText()+")",
                        analyzer2.summaryGenderData(analyzer2.mHashMap),
                        chartPanel.getSize()));
            chartPanel.validate();
        }
    }//GEN-LAST:event_jRadioButtonMenuItem_genderActionPerformed

    private void jRadioButtonMenuItem_dailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem_dailyActionPerformed
        // TODO add your handling code here:
        if (!analyzer.mHashMap.isEmpty()) {
            chartPanel.removeAll();
            chartPanel.add(new StackedBarChart(
                    "Daily Message",
                    analyzer.summaryMessageFrequencyData(analyzer.mHashMap),
                    analyzer2.summaryMessageFrequencyData(analyzer2.mHashMap),
                    topicTextField1.getText(),
                    topicTextField2.getText(),
                    chartPanel.getSize()));
            chartPanel.validate();
        }
    }//GEN-LAST:event_jRadioButtonMenuItem_dailyActionPerformed

    private void jRadioButtonMenuItem_ratioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem_ratioActionPerformed
        // TODO add your handling code here:
        if (!analyzer.mHashMap.isEmpty()) {
            chartPanel.removeAll();
            chartPanel.add(new StackedBarChart(
                    "Follower/Friend Ratio",
                    analyzer.summaryFollowerFriendRatio(analyzer.mHashMap),
                    analyzer2.summaryFollowerFriendRatio(analyzer2.mHashMap),
                    topicTextField1.getText(),
                    topicTextField2.getText(),
                    chartPanel.getSize()));
            chartPanel.validate();
        }
    }//GEN-LAST:event_jRadioButtonMenuItem_ratioActionPerformed

    private void jRadioButtonMenuItem_urlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem_urlActionPerformed
        // TODO add your handling code here:
        if (!analyzer.mHashMap.isEmpty()) {
            chartPanel.removeAll();
            chartPanel.add(new BarChart(
                    "ProfileURL ("+topicTextField1.getText()+")",
                    analyzer.summaryProfileURL(analyzer.mHashMap),
                    topicTextField1.getText(),
                    chartPanel.getSize(),
                    Color.RED));
            chartPanel.add(new BarChart(
                    "ProfileURL ("+topicTextField2.getText()+")",
                    analyzer2.summaryProfileURL(analyzer2.mHashMap),
                    topicTextField2.getText(),
                    chartPanel.getSize(),
                            Color.BLUE));
            chartPanel.validate();
        }
    }//GEN-LAST:event_jRadioButtonMenuItem_urlActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                
                HashMap[] hashs = fileProcessor.openFile(file);
                
                jLabel1.setText("Load file sucessful!");
                
                analyzer.mHashMap = hashs[0];
                analyzer2.mHashMap = hashs[1];
              
                userCount1.setText(String.valueOf(analyzer.mHashMap.size()));
                userCount2.setText(String.valueOf(analyzer2.mHashMap.size()));
                
                /* Update the chart panel. */
                chartPanel.removeAll();

                if (jRadioButtonMenuItem_daily.isSelected()) {
                    chartPanel.add(new StackedBarChart(
                            "Daily Message",
                            analyzer.summaryMessageFrequencyData(analyzer.mHashMap),
                            analyzer2.summaryMessageFrequencyData(analyzer2.mHashMap),
                            topicTextField1.getText(),topicTextField2.getText(),
                            chartPanel.getSize()));
                }

                else if (jRadioButtonMenuItem_gender.isSelected()) {
                    chartPanel.add(new PieChart(
                            "Gender ("+topicTextField1.getText()+")",
                            analyzer.summaryGenderData(analyzer.mHashMap),
                            chartPanel.getSize()));

                    chartPanel.add(new PieChart(
                            "Gender ("+topicTextField2.getText()+")",
                            analyzer2.summaryGenderData(analyzer2.mHashMap),
                            chartPanel.getSize()));
                }

                else if (jRadioButtonMenuItem_ratio.isSelected()) {
                    chartPanel.add(new StackedBarChart(
                            "Follower/Friend Ratio",
                            analyzer.summaryFollowerFriendRatio(analyzer.mHashMap),
                            analyzer2.summaryFollowerFriendRatio(analyzer2.mHashMap),
                            topicTextField1.getText(),topicTextField2.getText(),
                            chartPanel.getSize()));
                }

                else if(jRadioButtonMenuItem_url.isSelected()) {
                    chartPanel.add(new BarChart(
                    "ProfileURL ("+topicTextField1.getText()+")",
                            analyzer.summaryProfileURL(analyzer.mHashMap),
                            topicTextField1.getText(),
                            chartPanel.getSize(),
                            Color.RED));
                    chartPanel.add(new BarChart(
                    "ProfileURL ("+topicTextField2.getText()+")",
                    analyzer2.summaryProfileURL(analyzer2.mHashMap),
                    topicTextField2.getText(),
                    chartPanel.getSize(),
                            Color.BLUE));
                }

                chartPanel.validate();

        } 
        else {
                System.out.println("Open command cancelled by user.");
        }
 
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showSaveDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                
                
                if (!analyzer.mHashMap.isEmpty() && !analyzer2.mHashMap.isEmpty()) {
                    fileProcessor.saveFile(file, analyzer.mHashMap, analyzer2.mHashMap);
                }
                
                jLabel1.setText("Save file sucessful!");
        } 
        else {
                System.out.println("Open command cancelled by user.");
        }
 
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AboutBox box = new AboutBox(this);
        box.setLocationRelativeTo(this);
        box.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        HelpBox box = new HelpBox(this);
        box.setLocationRelativeTo(this);
        box.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    class TweetSearcher extends SwingWorker<String, Object>{

        @Override
        protected String doInBackground() throws Exception {

            jProgressBar2.setIndeterminate(true);
            
            jLabel1.setText("Getting tweets...");
            
            /* Get messages */
            if(!analyzer.GetMessageCorpus(topicTextField1.getText(), Integer.valueOf(tweetsPerPageTextField.getText())) ||
                    !analyzer2.GetMessageCorpus(topicTextField2.getText(), Integer.valueOf(tweetsPerPageTextField.getText()))) {
                return "Failed.";
            }
            
            
            jLabel1.setText("Getting user info...");
            
            /* Get user information. */
            if (!analyzer.MessageStats(analyzer.mMessageCorpus) ||
                    !analyzer2.MessageStats(analyzer2.mMessageCorpus)) {
                return "Failed.";
            }
            
            userCount1.setText(String.valueOf(analyzer.mHashMap.size()));
            userCount2.setText(String.valueOf(analyzer2.mHashMap.size()));
            
            return "Success!";
        }

        @Override
        protected void done() {
            chartPanel.removeAll();

            if (jRadioButtonMenuItem_daily.isSelected()) {
                chartPanel.add(new StackedBarChart(
                        "Daily Message",
                        analyzer.summaryMessageFrequencyData(analyzer.mHashMap),
                        analyzer2.summaryMessageFrequencyData(analyzer2.mHashMap),
                        topicTextField1.getText(),topicTextField2.getText(),
                        chartPanel.getSize()));
            }

            else if (jRadioButtonMenuItem_gender.isSelected()) {
                chartPanel.add(new PieChart(
                        "Gender ("+topicTextField1.getText()+")",
                        analyzer.summaryGenderData(analyzer.mHashMap),
                        chartPanel.getSize()));

                chartPanel.add(new PieChart(
                        "Gender ("+topicTextField2.getText()+")",
                        analyzer2.summaryGenderData(analyzer2.mHashMap),
                        chartPanel.getSize()));
            }

            else if (jRadioButtonMenuItem_ratio.isSelected()) {
                chartPanel.add(new StackedBarChart(
                        "Follower/Friend Ratio",
                        analyzer.summaryFollowerFriendRatio(analyzer.mHashMap),
                        analyzer2.summaryFollowerFriendRatio(analyzer2.mHashMap),
                        topicTextField1.getText(),topicTextField2.getText(),
                        chartPanel.getSize()));
            }

            else if(jRadioButtonMenuItem_url.isSelected()) {
                chartPanel.add(new BarChart(
                    "ProfileURL ("+topicTextField1.getText()+")",
                        analyzer.summaryProfileURL(analyzer.mHashMap),
                        topicTextField1.getText(),
                        chartPanel.getSize(),
                            Color.RED));
                chartPanel.add(new BarChart(
                    "ProfileURL ("+topicTextField2.getText()+")",
                    analyzer2.summaryProfileURL(analyzer2.mHashMap),
                    topicTextField2.getText(),
                    chartPanel.getSize(),
                            Color.BLUE));
            }

            chartPanel.validate();
            
            try {
                jLabel1.setText(this.get());
            } catch (InterruptedException ex) {
                Logger.getLogger(TwitterAnalyzerView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExecutionException ex) {
                Logger.getLogger(TwitterAnalyzerView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            jProgressBar2.setIndeterminate(false);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JDialog fileDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_daily;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_gender;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_ratio;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_url;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField topicTextField1;
    private javax.swing.JTextField topicTextField2;
    private javax.swing.JTextField tweetsPerPageTextField;
    private javax.swing.JLabel userCount1;
    private javax.swing.JLabel userCount2;
    // End of variables declaration//GEN-END:variables
}


